"""add activity system

Revision ID: 0c4ff90bda51
Revises: 84301830a3d1
Create Date: 2026-09-08 16:39:15.366819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4ff90bda51'
down_revision: Union[str, Sequence[str], None] = '84301830a3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_activity_types_code'), 'activity_types', ['code'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_at > start_at', name='ck_activity_end_after_start'),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type_id'), 'activities', ['activity_type_id'], unique=False)
    op.create_index(op.f('ix_activities_end_at'), 'activities', ['end_at'], unique=False)
    op.create_index(op.f('ix_activities_start_at'), 'activities', ['start_at'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_start_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_end_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_activity_types_code'), table_name='activity_types')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
