"""add exercise tracking

Revision ID: 4ae9c633ee49
Revises: 658a13c2e77e
Create Date: 2026-09-08 17:28:58.551589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae9c633ee49'
down_revision: Union[str, Sequence[str], None] = '658a13c2e77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_types_user_id'), 'exercise_types', ['user_id'], unique=False)
    op.create_table('exercise_sessions',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('overall_intensity', sa.SmallInteger(), nullable=True),
    sa.Column('calories_estimated', sa.Integer(), nullable=True),
    sa.CheckConstraint('calories_estimated >= 0', name='ck_exercise_calories_non_negative'),
    sa.CheckConstraint('overall_intensity >= 1 AND overall_intensity <= 5', name='ck_exercise_overall_intensity_range'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('cardio_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_session_id', sa.UUID(), nullable=False),
    sa.Column('cardio_type', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('calories_estimated', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('average_speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('incline_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.CheckConstraint('calories_estimated >= 0', name='ck_cardio_calories_non_negative'),
    sa.CheckConstraint('distance_km >= 0', name='ck_cardio_distance_non_negative'),
    sa.CheckConstraint('duration_seconds > 0', name='ck_cardio_duration_positive'),
    sa.CheckConstraint('incline_percent >= 0', name='ck_cardio_incline_non_negative'),
    sa.ForeignKeyConstraint(['exercise_session_id'], ['exercise_sessions.activity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardio_entries_exercise_session_id'), 'cardio_entries', ['exercise_session_id'], unique=False)
    op.create_table('exercise_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_type_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.CheckConstraint('order_index >= 0', name='ck_exercise_entry_order_non_negative'),
    sa.ForeignKeyConstraint(['exercise_session_id'], ['exercise_sessions.activity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_type_id'], ['exercise_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_entries_exercise_session_id'), 'exercise_entries', ['exercise_session_id'], unique=False)
    op.create_index(op.f('ix_exercise_entries_exercise_type_id'), 'exercise_entries', ['exercise_type_id'], unique=False)
    op.create_table('exercise_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_entry_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('set_type', sa.String(length=30), nullable=True),
    sa.CheckConstraint('distance_km >= 0', name='ck_exercise_set_distance_non_negative'),
    sa.CheckConstraint('duration_seconds >= 0', name='ck_exercise_set_duration_non_negative'),
    sa.CheckConstraint('repetitions >= 0', name='ck_exercise_set_repetitions_non_negative'),
    sa.CheckConstraint('set_number > 0', name='ck_exercise_set_number_positive'),
    sa.CheckConstraint('weight_kg >= 0', name='ck_exercise_set_weight_non_negative'),
    sa.ForeignKeyConstraint(['exercise_entry_id'], ['exercise_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_entry_id', 'set_number', name='uq_exercise_set_number')
    )
    op.create_index(op.f('ix_exercise_sets_exercise_entry_id'), 'exercise_sets', ['exercise_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_sets_exercise_entry_id'), table_name='exercise_sets')
    op.drop_table('exercise_sets')
    op.drop_index(op.f('ix_exercise_entries_exercise_type_id'), table_name='exercise_entries')
    op.drop_index(op.f('ix_exercise_entries_exercise_session_id'), table_name='exercise_entries')
    op.drop_table('exercise_entries')
    op.drop_index(op.f('ix_cardio_entries_exercise_session_id'), table_name='cardio_entries')
    op.drop_table('cardio_entries')
    op.drop_table('exercise_sessions')
    op.drop_index(op.f('ix_exercise_types_user_id'), table_name='exercise_types')
    op.drop_table('exercise_types')
    # ### end Alembic commands ###
