"""add study tracking

Revision ID: 658a13c2e77e
Revises: 0c4ff90bda51
Create Date: 2026-09-08 16:53:09.315256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658a13c2e77e'
down_revision: Union[str, Sequence[str], None] = '0c4ff90bda51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_subjects_user_id'), 'study_subjects', ['user_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('problems_solved', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=True),
    sa.Column('what_studied', sa.Text(), nullable=True),
    sa.Column('what_struggled', sa.Text(), nullable=True),
    sa.Column('what_learned', sa.Text(), nullable=True),
    sa.CheckConstraint('confidence >= 1 AND confidence <= 5', name='ck_study_confidence_range'),
    sa.CheckConstraint('problems_solved >= 0', name='ck_study_problems_solved_non_negative'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['study_subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_study_sessions_subject_id'), 'study_sessions', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_sessions_subject_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_study_subjects_user_id'), table_name='study_subjects')
    op.drop_table('study_subjects')
    # ### end Alembic commands ###
