"""add reading and meditation tracking

Revision ID: 8b7763cab4c4
Revises: f2bc01f41eeb
Create Date: 2026-09-08 20:55:38.112087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7763cab4c4'
down_revision: Union[str, Sequence[str], None] = 'f2bc01f41eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_user_id'), 'books', ['user_id'], unique=False)
    op.create_table('meditation_logs',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('meditation_type', sa.String(length=50), nullable=True),
    sa.Column('quality', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('quality >= 1 AND quality <= 5', name='ck_meditation_quality_range'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('reading_logs',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.String(length=150), nullable=True),
    sa.Column('what_learned', sa.String(length=2000), nullable=True),
    sa.CheckConstraint('pages_read >= 0', name='ck_reading_pages_non_negative'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_reading_logs_book_id'), 'reading_logs', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_logs_book_id'), table_name='reading_logs')
    op.drop_table('reading_logs')
    op.drop_table('meditation_logs')
    op.drop_index(op.f('ix_books_user_id'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
