"""add sleep and walking tracking

Revision ID: f2bc01f41eeb
Revises: 4ae9c633ee49
Create Date: 2026-09-08 20:49:53.401002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bc01f41eeb'
down_revision: Union[str, Sequence[str], None] = '4ae9c633ee49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_logs',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('wake_count', sa.Integer(), nullable=False),
    sa.Column('quality', sa.SmallInteger(), nullable=True),
    sa.Column('restedness', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('quality >= 1 AND quality <= 5', name='ck_sleep_quality_range'),
    sa.CheckConstraint('restedness >= 1 AND restedness <= 5', name='ck_sleep_restedness_range'),
    sa.CheckConstraint('wake_count >= 0', name='ck_sleep_wake_count_non_negative'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('walking_logs',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('activity_kind', sa.String(length=20), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('steps_source', sa.String(length=20), nullable=True),
    sa.Column('pace_seconds_per_km', sa.Integer(), nullable=True),
    sa.Column('calories_estimated', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.CheckConstraint('calories_estimated >= 0', name='ck_walking_calories_non_negative'),
    sa.CheckConstraint('distance_km >= 0', name='ck_walking_distance_non_negative'),
    sa.CheckConstraint('pace_seconds_per_km >= 0', name='ck_walking_pace_non_negative'),
    sa.CheckConstraint('steps >= 0', name='ck_walking_steps_non_negative'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walking_logs')
    op.drop_table('sleep_logs')
    # ### end Alembic commands ###
